### PR TITLE
Fix codeAsInSource

### LINKED ISSUE #97: incorrect code for nbTextWithCode with multiline string on same line as command
Compiling and running this file:

```nim
import nimib
nbInit
nbTextWithCode: """problem
solution"""
echo "nb.blk.code: ", nb.blk.code
```

last line of output is (when using `CodeAsInSource` now default):

```
nb.blk.code: """problem
```

while it should be (as it is when using `-d:nimibCodeFromAst`)

```
nb.blk.code: """problem
solution"""
```

fix to be done in code in `src/nimib/sources.nim`

### PR DESCRIPTION
**Pull request by HugoGranstrom**
Let's see if this works better now...

It took a day but I think I've found a somewhat non-chaotic implementation that seems to work. I added a few tests but I will add a few more and manually go through the docs to see if it looks OK. 

fixes #97 

## TODO
- [x] Handle comments at end of code blocks
- [x] Go through the docs and check for errors
  - [x] Penguin
  - [x] numerical
  - [x] cheatsheet
  - [x] mostaccio
  - [x] interactivity
  - [x] counter
  - [x] caesar
  - [x] hello
  - [x] files
  - [x] pythno
  - [x] nolan

### CODE REVIEW

**Comment by HugoGranstrom** [comment]
Ok, that seems to have fixed it but why did it work locally without any errors... 🤷

**Comment by pietroppeter** [comment]
Nice! Can you try also to remove the `when defined(nimibCodeFromAst)` in `t nimib.nim`?

**Comment by HugoGranstrom** [comment]
Something smells weird here, when the `defined(nimibCodeFromAst)` was included no errors. But when it was removed it gives an error at the very end (after the last test has been run with OK). I read somewhere that a plain `Error: execution of an external program failed:` means that the program returned a non-zero error code but I have idea how that could be dependent on this when-statement :/

**Comment by HugoGranstrom** [comment]
To make it even stranger, running it with `nim r` gives this error but doing ``nim c` and then running the executable doesn't give any errors

**Comment by HugoGranstrom** [comment]
Oh wait I'm just blind, there was a failed test 🤦

**Comment by pietroppeter** [comment]
ah, right, it is to be expected! In nim multiline string remove the first newline so CodeFromAst does not see it, while CodeAsInSource sees it as it is written. They are both right! Probably the easieast way to fix it would be a short template/proc used only in tests and added to the multiline strings involved here:

```nim
template normalizeMultilineStringLiteral(s: string) =
  when not defined(CodeFromAst):
    if s[0] == "\n":
      return s[1 ..< s.len]
```

**Comment by pietroppeter** [comment]
didn't see you already had the fix. fine as it is for me!

**Comment by HugoGranstrom** [comment]
> ah, right, it is to be expected! In nim [multiline string literal remove the first newline](https://nim-lang.github.io/Nim/manual.html#lexical-analysis-triple-quoted-string-literals) so CodeFromAst does not see it, while CodeAsInSource sees it as it is written. They are both right! Probably the easieast way to fix it would be a short template/proc used only in tests and added to the multiline strings involved here:

TIL :D

> didn't see you already had the fix. fine as it is for me!

It is the only case where it matters thus far so making a template only feels warranted when we have a few test that needs it 👍

**Comment by HugoGranstrom** [comment]
I've gone over the docs now and to my eyes, it looks like it's working but I would appreciate a second opinion on that 😅

**Review by pietroppeter — APPROVED** [review]

File: docsrc/interactivity.nim [hunk 1]
```diff
@@ -27,6 +27,8 @@ nbCode:
   ## Uncomment this line:
   ##script.addToDocAsJs()
 script.addToDocAsJs()
+
+nbText: "The complete code is:"
```
Comment (pietroppeter) [inline docsrc/interactivity.nim:31]: ah, no, sorry we cannot do it like this. `nbCodeToJsShowSource()` must come after the block. checking the document the code block is now disappeared (it is showing the code block of `nbText`). let's just remove this

**Review by pietroppeter — CHANGES_REQUESTED** [review]

File: docsrc/interactivity.nim (hunk 1 above)
Comment (HugoGranstrom) [reply docsrc/interactivity.nim:31]: Oh right... 🤦 It was part of the nbCodeToJs block. So we should add it to the partial instead then I guess?

Comment (pietroppeter) [reply docsrc/interactivity.nim:31]: you are right! we should find the block and then create a new code block with the code content. or in principle for this case we could just specify before the first code block that we will show also the nim code that will be compiled to javascript.

Comment (pietroppeter) [reply docsrc/interactivity.nim:31]: > I don't really understand this part.

that part means that we do not change anything in `nbCodeToJsShowSource` and we just add some text before the code blocks saying that the after the first code block, in the second code block we will show the nim source. just a patch and we delay the fix.

 > My understanding is that we throw the "nbJsScriptNimSource" partial out the window completely, and create a new code block in nbCodeToJsShowSource which takes the code from the closest nbCodeToJs block in nb.blocks?

yes this would be my second suggestion. but now that you say it like that, indeed I like better your suggestion of having a message (even a default message) to show in nbCodeToJsShowSource.

**Review by pietroppeter — APPROVED** [review]

File: docsrc/interactivity.nim (hunk 1 above)
Comment (pietroppeter) [reply docsrc/interactivity.nim]: yep, go ahead!
